name: readtrack
description: "Track your daily reading time and build a consistent reading habit."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  hive_flutter: ^1.1.0
  google_fonts: ^8.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  device_preview: ^1.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1A1A1A"
  image: "assets/app_logo.png"
  image_dark: "assets/app_logo.png"
  android_12:
    color: "#FFFFFF"
    color_dark: "#1A1A1A"
    image: "assets/app_logo.png"
    image_dark: "assets/app_logo.png"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/logo.png
